server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/barcochrist/config-service.git
          searchPaths: config-data
  security:
    user:
      name: root
      password: s3cr3t